# 网站标题
title: 我的机器人课程作业

# 网站描述
description: AI Robotics 课程作业整理

# 主题选择（可选以下主题）
theme: jekyll-theme-cayman
# theme: jekyll-theme-minimal
# theme: jekyll-theme-slate
# theme: jekyll-theme-architect

# 显示下载按钮（可选）
show_downloads: false
